### ISSUE TITLE
Downloading a TA Request gives a VA PDF 

### ISSUE THREAD

**Issue by scottwilson-nhm** [DiSSCo/ELViS#225]
When you are admin, you can download TA Requests as below:

![image](https://user-images.githubusercontent.com/58856468/110778332-1ec7a500-825a-11eb-89f3-03e048d02df6.png)

The PDF download however is a VA format PDF with questions that don't correspond to the TA questions:

![image](https://user-images.githubusercontent.com/58856468/110778472-4ae32600-825a-11eb-9d87-f4bdcc6c4b21.png)

We will need to be able to download TA Requests as PDFs for the User Selection Panels, but also for Host Validations which we are having to do offline - having a PDF of the TA form will be crucial for that.

**Comment by cannedit** [comment]
This issue is already identified (see Github issue #214) and we're working on it.

**Comment by cannedit** [comment]
This is solved now, so please test again.

**Comment by wouteraddink** [comment]
I cannot test this, still have an encoding issue with downloading the pdfs on my machine (even though I have a new Windows version), somehow these are seen as .txt.

**Comment by cannedit** [comment]
Is this happening in all browsers? The newest MS browser Edge is known to have some problems with PDF's ...
